- Python/palindrome.py
please add this pr for hacktoberfest2021
> palindrome number code in python

- C++/count_subset_of_given_difference.cpp
This counts the number of subsets having given difference
> Dynamic Programming problem 1

- C/stack_infix_postfix.c
- C/stack_parenthesis.c
1.parenthesis checking
it checks validity of a parenthesis expression
eg: 
()()()((())())   :valid
(())))))))     : invalid
2.infix to postfix
it converts infix to postfix using stack adt.
eg: input: (a+b)c(d-e/f)
output: ab+cdef/-
> added stack programs in c

- Food Ordering System using C++/Food_Order.cpp
- Food Ordering System using C++/readme.md
I've created a food ordering system project using c++.
> Online Food Ordering System using C++

- C++/ArmstrongNumber.cpp
- C++/FrequencyOfWords.cpp
Heyy
I have added two cpp program snippets. Hope it would help.
Following are the file names.
_I have made sure they are in the correct folder and the snippets are working._
- C++/ArmstrongNumber.cpp
- C++/FrequencyOfWords.cpp
Cheers!
> added 2 cpp files

- Python/Speech_To_Text.py
This python script actually converts the audio to text. With the help of PyAudio module in python.
> Speech to Text Python Script

- Python/password_generator.py
this is python pass generator, thanks sir for merging my PR
> add password_generator.py

- Python/ScreenShot.py
@razrexe I have made a screenshot python script. When you run the script after 5 seconds it will automatically take the screenshot and saves the image inside the folder.
> ScreenShot Python Script

- C/Sorting Using C/BubbleSort.c
- C/Sorting Using C/InsertionSort.c
- C/Sorting Using C/MergeSort.c
- C/Sorting Using C/QuickSort.c
- C/Sorting Using C/SelectionSort.c
- Bubble Sort
- Insertion Sort
- Merge Sort
- Quick Sort
- Selection Sort
> Added 5 types of sorting programs in C

- Assembly/helloworld.asm
Added X86 Assembly hello world program
> Hello world in x86 assembly

- C++/Fast_power.cpp
- C++/Rat_in_a_maze.cpp
My first PR in Hacktoberfest 2021.
Let me know if there's any problem :)
> Famous problem on recursion

- Food Delivery Website Frontend/restaurant/css/namelist.css
- Food Delivery Website Frontend/restaurant/list1.html
- Food Delivery Website Frontend/restaurant/list2.html
- Food Delivery Website Frontend/restaurant/lists3.html
- Food Delivery Website Frontend/restaurant/lists4.html
**Before:** 
https://user-images.githubusercontent.com/77449219/135624544-27016ced-43ac-4a9c-9960-f1295d5136af.mp4
**After:**
https://user-images.githubusercontent.com/77449219/135624605-6bd3fac8-b542-41d1-8d75-16a914a75b5c.mp4
**Corrections made:**
> All Menu Lists fixed in restaurant (frontend) website

- C/stack_using_array
Heyy
I have added one c program snippet. Hope it would help.
Following is the file name.
I have made sure they are in the correct folder and the snippets are working.
C/stack_using_array
The program is used to implement stack using array and work on the basic functions of stack.
Cheers!
> Added a program of stack using array

- C++/Round_Robin_Scheduling_with_zero_arrival_time.cpp
Its C++ implementation of Round Robin scheduling where we have assumed arrival times as 0, so turn around and completion times are the same.
#Hacktoberfest2021
> Round Robin Time Scheduling with zero arrival time - C++

- C++/Print-all-subsequences-of-a-string.cpp
Please accept my PR. I hope this is helpful
> Added String Program

- C++/Median-of-two-sorted-arrays-of-different-sizes.cpp
**Added Median of two sorted arrays of different sizes program. Please accept my PR. I hope this is helpful.**
> Added array program

- Blogging Website Frontend/assets/styles.css
- Blogging Website Frontend/blog.html
Added functionality of search blog by title in the blog website (frontend)
**Demo**:
https://user-images.githubusercontent.com/77449219/135698710-43379acf-b9d9-44b6-84c9-9311d0ff5f14.mp4
> Made search blog feature functional

- ngrok/ngrok.md
> ✨ ngrok instructions and installation added.

- LOGIN PAGE USING C++/Readme.md
- LOGIN PAGE USING C++/login.cpp
I've added project of login page created using c++.
> LOGIN PAGE USING C++

- Phone book using c++/phonebook.cpp
- Phone book using c++/readme.md
I've added project of phone book using c++.
> Phone Book Using C++

- C++/Sudoku_game.cpp
> Sudoku_Game.cpp

- JavaScript Clock/index.html
Added JS clock for #hacktoberfest challenge
> Added JS clock

- .gitmodules
Added a react "to do list" app to the main repo
> added react task tracker to project

- Learning Management System/LMS.cpp
- Learning Management System/readme.md
I 've added Learning management system using c++.
> Learning Management System Using C++

- C++/insertion sort.cpp
- C++/quick sort.cpp
- C++/shell sort.cpp
Code for insertion sort in C++
> Create insertion sort.cpp
